openapi: "3.0.0"
paths:
  /databases:
    get:
      summary: Get all databases
      operationId: getDatabases
      tags:
        - databases
      parameters:
        - name: limit
          in: query
          ...
      responses:
        ...
    post:
      summary: Create a database
      operationId: createDatabase
      ...
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      ...
info:
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string